import React from 'react'
export default function Navbar2() {
  return (
   <div>
    <div style={{flex: '0 0 100%', maxWidth: '100%', width: '100%', float: 'left', margin: '0px 0px 10px', padding: '10px 10px 5px', marginBottom: '10px', background: 'rgb(255, 255, 255) none repeat scroll 0% 0% / auto padding-box border-box', border: '1px solid rgb(204, 204, 204)', paddingTop: '10px', paddingRight: '10px', paddingLeft: '10px', paddingBottom: '5px', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box', position: 'relative', textDecoration: 'none solid rgb(80, 80, 80)', minHeight: '1px'}}>
    <div style={{margin: '0px', padding: '0px', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>
        <div style={{margin: '0px', padding: '0px 0px 5px', display: 'inline-block', paddingBottom: '5px', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>
            <div tabIndex="4" captionlabel="lblPCBDataUpload" data="To use this Function Please Upload your PCB Data" style={{margin: '0px', padding: '0px', fontSize: '12.8px', position: 'relative', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>
                <div style={{border: '1px solid rgb(222, 222, 222)', borderRadius: '3px', margin: '0px 5px 0px 0px', padding: '5px', opacity: '0.6', cursor: 'not-allowed', backgroundColor: 'rgb(239, 239, 239)', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}><label style={{margin: '0px', padding: '0px', fontSize: '12.8px', boxSizing: 'border-box', display: 'inline-block', marginBottom: '0px', width: '20px', height: '20px', background: 'rgba(0, 0, 0, 0) url("https://be.eurocircuits.com/shop/assembly/images/asm_imgs_sprite.png?v=0.02") repeat scroll -205px -150px / auto padding-box border-box', verticalAlign: 'bottom', fontWeight: 400, color: 'rgb(85, 85, 85)', maxWidth: '100%'}}></label> <span xmlresource="btnPCBViewer" style={{fontSize: '12px', margin: '0px', padding: '0px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>PCB Viewer</span></div>
            </div>
        </div>
        <div style={{margin: '0px', padding: '0px 0px 5px', display: 'inline-block', paddingBottom: '5px', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>
            <div tabIndex="5" captionlabel="lblPCBDataUpload" data="To use this Function Please Upload your PCB Data" style={{margin: '0px', padding: '0px', fontSize: '12.8px', position: 'relative', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>
                <div style={{border: '1px solid rgb(222, 222, 222)', borderRadius: '3px', margin: '0px 5px 0px 0px', padding: '5px', opacity: '0.6', cursor: 'not-allowed', backgroundColor: 'rgb(239, 239, 239)', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}><label style={{margin: '0px', padding: '0px', fontSize: '12.8px', boxSizing: 'border-box', display: 'inline-block', marginBottom: '0px', width: '20px', height: '20px', background: 'rgba(0, 0, 0, 0) url("https://be.eurocircuits.com/shop/assembly/images/asm_imgs_sprite.png?v=0.02") repeat scroll -304px -90px / auto padding-box border-box', verticalAlign: 'bottom', fontWeight: 400, color: 'rgb(85, 85, 85)', maxWidth: '100%'}}></label> <span xmlresource="btnPCBViewer" style={{fontSize: '12px', margin: '0px', padding: '0px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>PCB Checker</span></div>
            </div>
        </div>
        <div style={{margin: '0px', padding: '0px 0px 5px', display: 'inline-block', paddingBottom: '5px', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>
            <div captionlabel="lblPCBDataUpload" tabIndex="6" data="To use this Function Please Upload your PCB Data" style={{margin: '0px', padding: '0px', fontSize: '12.8px', position: 'relative', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>
                <div style={{border: '1px solid rgb(222, 222, 222)', borderRadius: '3px', margin: '0px 5px 0px 0px', padding: '5px', opacity: '0.6', cursor: 'not-allowed', backgroundColor: 'rgb(239, 239, 239)', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}><img src="resources/Panel_Editor_Disable.svg" style={{margin: '-3px 0px 0px', padding: '0px', height: '20px', marginTop: '-3px', boxSizing: 'border-box', verticalAlign: 'middle', borderStyle: 'none', border: '0px none rgb(80, 80, 80)'}} /> <span xmlresource="btnPanelEditor" style={{fontSize: '12px', margin: '0px', padding: '0px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>Panel Editor</span></div>
            </div>
        </div>
        <div style={{margin: '0px', padding: '0px 0px 5px', display: 'inline-block', paddingBottom: '5px', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>
            <div tabIndex="7" data="<table className='m-lr-5'> <tr><td><div className='btn_header XmlLanguageTag' xmlResource=&quot;btnBuildupEditorInfo&quot;>Buildup Editor</div><div className='XmlLanguageTag' xmlResource=&quot;btnBuildupEditorInfo&quot;><div>Defines the build of your PCB, such as Number of Layers, Sequence, copper thickness, position in the build and possible blind and burried vias. There are more than 900 pre-defined builds available.</div> <br /><a href='https://www.eurocircuits.com/blog/Buildup-wizard-and-layer-editor-updated/' className='lnk_service' target='_blank' >Read more</a> </div></td> </tr> </table>" style={{border: '1px solid rgb(128, 128, 128)', borderRadius: '3px', margin: '0px 5px 0px 0px', padding: '5px', cursor: 'pointer', fontSize: '12px', position: 'relative', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>
                <div style={{margin: '0px', padding: '0px', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}><span style={{fontSize: '12px', margin: '0px', padding: '0px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}><img src="resources/BuildUp_Editor_Enable.svg" style={{margin: '-3px 0px 0px', padding: '0px', height: '20px', marginTop: '-3px', boxSizing: 'border-box', verticalAlign: 'middle', borderStyle: 'none', border: '0px none rgb(80, 80, 80)'}} /> <img src="resources/BuildUp_Editor_White.svg" style={{margin: '-3px 0px 0px', padding: '0px', display: 'none', height: '20px', marginTop: '-3px', boxSizing: 'border-box', verticalAlign: 'middle', borderStyle: 'none', border: '0px none rgb(80, 80, 80)'}} /></span> <span xmlresource="btnBuildupEditor" style={{fontSize: '12px', margin: '0px', padding: '0px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>Buildup Editor</span></div>
            </div>
        </div>
        <div style={{margin: '0px', padding: '0px 0px 5px', display: 'inline-block', paddingBottom: '5px', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>
            <div tabIndex="8" data="<table className='m-lr-5'> <tr><td><div className='btn_header XmlLanguageTag' xmlResource=&quot;btnClassificationInfo&quot;>Classification</div><div className='XmlLanguageTag' xmlResource=&quot;btnClassificationInfo&quot;><div>We use “pattern classes” and “drill classes” as convenient methods to measure the Manufacturability of the PCB. This will determine if your Design is Poolable or not and may also have an impact on the price.</div> <br /><a href='https://www.eurocircuits.com/pcb-design-guidelines-classification/' className='lnk_service' target='_blank' >Read more</a> </div></td> </tr> </table>" style={{border: '1px solid rgb(128, 128, 128)', borderRadius: '3px', margin: '0px 5px 0px 0px', padding: '5px', cursor: 'pointer', fontSize: '12px', position: 'relative', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>
                <div style={{margin: '0px', padding: '0px', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}><span style={{fontSize: '12px', margin: '0px', padding: '0px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}><img src="resources/Classification_Editor_Enable.svg" style={{margin: '-3px 0px 0px', padding: '0px', height: '20px', marginTop: '-3px', boxSizing: 'border-box', verticalAlign: 'middle', borderStyle: 'none', border: '0px none rgb(80, 80, 80)'}} /> <img src="resources/Classification_Editor_White.svg" style={{margin: '-3px 0px 0px', padding: '0px', display: 'none', height: '20px', marginTop: '-3px', boxSizing: 'border-box', verticalAlign: 'middle', borderStyle: 'none', border: '0px none rgb(80, 80, 80)'}} /></span> <span xmlresource="btnClassification" style={{fontSize: '12px', margin: '0px', padding: '0px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>Classification</span></div>
            </div>
        </div>
        <div style={{margin: '0px', padding: '0px 0px 5px', display: 'inline-block', paddingBottom: '5px', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>
            <div tabIndex="9" captionlabel="lblPCBDataUpload" data="To use this Function Please Upload your PCB Data" style={{margin: '0px', padding: '0px', fontSize: '12.8px', position: 'relative', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>
                <div style={{border: '1px solid rgb(222, 222, 222)', borderRadius: '3px', margin: '0px 5px 0px 0px', padding: '5px', opacity: '0.6', cursor: 'not-allowed', backgroundColor: 'rgb(239, 239, 239)', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}><img src="resources/layer_gray.svg" style={{margin: '-3px 0px 0px', padding: '0px', height: '20px', marginTop: '-3px', boxSizing: 'border-box', verticalAlign: 'middle', borderStyle: 'none', border: '0px none rgb(80, 80, 80)'}} /> <span xmlresource="btnLayerEditor" style={{fontSize: '12px', margin: '0px', padding: '0px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>Layer Editor</span></div>
            </div>
        </div>
        <div style={{margin: '0px', padding: '0px 0px 5px', display: 'inline-block', paddingBottom: '5px', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>
            <div tabIndex="10" captionlabel="lblPCBDataUpload" data="To use this Function Please Upload your PCB Data" style={{margin: '0px', padding: '0px', fontSize: '12.8px', position: 'relative', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>
                <div style={{border: '1px solid rgb(222, 222, 222)', borderRadius: '3px', margin: '0px 5px 0px 0px', padding: '5px', opacity: '0.6', cursor: 'not-allowed', backgroundColor: 'rgb(239, 239, 239)', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}><img src="resources/Drill_Editor_Disable.svg" style={{margin: '-3px 0px 0px', padding: '0px', height: '20px', marginTop: '-3px', boxSizing: 'border-box', verticalAlign: 'middle', borderStyle: 'none', border: '0px none rgb(80, 80, 80)'}} /> <span xmlresource="btnDrillEditor" style={{fontSize: '12px', margin: '0px', padding: '0px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>Drill Editor</span></div>
            </div>
        </div>
        <div style={{margin: '0px', padding: '0px 0px 5px', display: 'inline-block', paddingBottom: '5px', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>
            <div tabIndex="11" captionlabel="lblPCBDataUpload" data="To use this Function Please Upload your PCB Data" style={{margin: '0px', padding: '0px', fontSize: '12.8px', position: 'relative', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>
                <div style={{border: '1px solid rgb(222, 222, 222)', borderRadius: '3px', margin: '0px 5px 0px 0px', padding: '5px', opacity: '0.6', cursor: 'not-allowed', backgroundColor: 'rgb(239, 239, 239)', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}><img src="resources/Outline_Editor_Disable.svg" style={{margin: '-3px 0px 0px', padding: '0px', height: '20px', marginTop: '-3px', boxSizing: 'border-box', verticalAlign: 'middle', borderStyle: 'none', border: '0px none rgb(80, 80, 80)'}} /> <span xmlresource="btnOutlineEditor" style={{fontSize: '12px', margin: '0px', padding: '0px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>Outline/Milling Editor</span></div>
            </div>
        </div>
        <div style={{margin: '0px', padding: '0px 0px 5px', display: 'inline-block', paddingBottom: '5px', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>
            <div tabIndex="12" captionlabel="lblPCBDataUpload" data="To use this Function Please Upload your PCB Data" style={{margin: '0px', padding: '0px', fontSize: '12.8px', position: 'relative', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>
                <div style={{border: '1px solid rgb(222, 222, 222)', borderRadius: '3px', margin: '0px 5px 0px 0px', padding: '5px', opacity: '0.6', cursor: 'not-allowed', backgroundColor: 'rgb(239, 239, 239)', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}><img src="resources/Solderpaste_gray.svg" style={{margin: '-3px 0px 0px', padding: '0px', height: '20px', marginTop: '-3px', boxSizing: 'border-box', verticalAlign: 'middle', borderStyle: 'none', border: '0px none rgb(80, 80, 80)'}} /> <span xmlresource="btnPasteEditor" style={{fontSize: '12px', margin: '0px', padding: '0px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>Paste Editor</span></div>
            </div>
        </div>
        <div style={{margin: '0px', padding: '0px 0px 5px', display: 'inline-block', paddingBottom: '5px', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>
            <div tabIndex="13" captionlabel="lblPCBDataUpload" data="To use this Function Please Upload your PCB Data" style={{margin: '0px', padding: '0px', fontSize: '12.8px', position: 'relative', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>
                <div style={{border: '1px solid rgb(222, 222, 222)', borderRadius: '3px', margin: '0px 5px 0px 0px', padding: '5px', opacity: '0.6', cursor: 'not-allowed', backgroundColor: 'rgb(239, 239, 239)', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}><img src="resources/Marking_Editor_Disable.svg" style={{margin: '-3px 0px 0px', padding: '0px', height: '20px', marginTop: '-3px', boxSizing: 'border-box', verticalAlign: 'middle', borderStyle: 'none', border: '0px none rgb(80, 80, 80)'}} /> <span xmlresource="btnMarkingEditor" style={{fontSize: '12px', margin: '0px', padding: '0px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>Marking Editor</span></div>
                <div style={{minWidth: '375px', marginBottom: '0px', left: 'auto', top: '30px', display: 'none', right: '0px', margin: '0px', padding: '8px', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box', animation: '5s ease 0s 1 normal none running ecpart-tips', whiteSpace: 'normal', cursor: 'text', position: 'absolute', borderWidth: '1px', borderStyle: 'solid', borderColor: 'rgb(42, 159, 0)', borderRadius: '5px', backgroundColor: 'rgb(248, 254, 244)', color: 'rgb(51, 51, 51)', zIndex: 1001, maxWidth: '220px', wordBreak: 'break-word', textAlign: 'left'}}><span style={{margin: '5px 0px 0px', padding: '0px', fontFamily: '"Open sans"', boxSizing: 'border-box', marginTop: '5px', fontSize: '12px', lineHeight: '16px'}}><span xmlresource="lblPCBDataUpload" style={{margin: '5px 0px 0px', padding: '0px', fontFamily: '"Open sans"', boxSizing: 'border-box', marginTop: '5px', fontSize: '12px', lineHeight: '16px'}}>To use this Function Please Upload your PCB Data</span></span> <span style={{margin: '0px', padding: '0px', left: 'auto', right: '20px', fontFamily: '"Open sans"', boxSizing: 'border-box', height: '10px', width: '10px', display: 'block', overflow: 'hidden', transform: 'none', borderImage: 'none', background: 'rgb(248, 254, 244) none repeat scroll 0% 0% / auto padding-box border-box', top: '-6px', borderRight: '0px none rgb(51, 51, 51)', borderBottom: '0px none rgb(51, 51, 51)', position: 'absolute', borderTop: '1px solid rgb(42, 159, 0)', borderLeft: '1px solid rgb(42, 159, 0)', marginTop: '0px', fontSize: '12px', lineHeight: '16px'}}></span></div>
            </div>
        </div>
        <div style={{margin: '0px', padding: '0px 0px 5px', display: 'inline-block', paddingBottom: '5px', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>
            <div tabIndex="15" data="To use this Function Please Select Defined Impedance pool service" captionlabel="lblSelectDefinedImpedence" style={{margin: '0px', padding: '0px', fontSize: '12.8px', position: 'relative', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>
                <div style={{border: '1px solid rgb(222, 222, 222)', borderRadius: '3px', margin: '0px 5px 0px 0px', padding: '5px', opacity: '0.6', cursor: 'not-allowed', backgroundColor: 'rgb(239, 239, 239)', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}><i style={{fontSize: '14px', margin: '0px', padding: '0px', boxSizing: 'border-box', display: 'inline-block', fontStyle: 'normal', fontVariant: 'normal', fontKerning: 'auto', fontOpticalSizing: 'auto', fontFeatureSettings: 'normal', fontVariationSettings: 'normal', fontWeight: 400, fontStretch: '100%', lineHeight: '14px', fontFamily: 'FontAwesome', textRendering: 'auto', WebkitFontSmoothing: 'antialiased'}}></i> <span xmlresource="btnDefImpCalc" style={{fontSize: '12px', margin: '0px', padding: '0px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>Impedance Calculator</span></div>
            </div>
        </div>
        <div style={{margin: '0px', padding: '0px 0px 5px', display: 'inline-block', paddingBottom: '5px', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>
            <div tabIndex="14" captionlabel="lblPCBDataUpload" data="To use this Function Please Upload your PCB Data" style={{margin: '0px', padding: '0px', fontSize: '12.8px', position: 'relative', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>
                <div style={{border: '1px solid rgb(222, 222, 222)', borderRadius: '3px', margin: '0px 5px 0px 0px', padding: '5px', opacity: '0.6', cursor: 'not-allowed', backgroundColor: 'rgb(239, 239, 239)', fontSize: '12.8px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}><img src="resources/Pixture_Editor_Disable.svg" style={{margin: '-3px 0px 0px', padding: '0px', height: '20px', marginTop: '-3px', boxSizing: 'border-box', verticalAlign: 'middle', borderStyle: 'none', border: '0px none rgb(80, 80, 80)'}} /> <span xmlresource="btnPixtureEditor" style={{fontSize: '12px', margin: '0px', padding: '0px', fontFamily: '"Open sans"', boxSizing: 'border-box'}}>Pixture Editor</span></div>
            </div>
        </div>
    </div>
</div>
</div>
  )
}
